### ISSUE TITLE
Question - Elaboration time day-05

### ISSUE THREAD

**Issue by AndreaGero** [jhrcook/advent-of-code-2023-rust#1]
Hi, I got basically the same approach of you, but when finding solution for part 2 it takes a very long time and after 5 minutes I didn't have it, I think because iterating all over the range of seed takes a long time if the range contains millions of elements.

How long did it takes to you to get the solution?

**Comment by jhrcook** [comment]
Takes about 1.5 minutes on my computer (using the `--release` flag). I may have gotten lucky that with my input, the brute force method isn't awful. If I have the time and desire, I may come back to Day 5 and figure out the trick, though.
